NAME := identify
CXX := c++
CXXFLAGS := -Wall -Wextra -Werror -std=c++98
SRCS := main.cpp identify.cpp
OBJS := $(SRCS:.cpp=.o)


all: $(NAME)


$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^


%.o: %.cpp Base.hpp A.hpp B.hpp C.hpp
	$(CXX) $(CXXFLAGS) -c $< -o $@


clean:
	rm -f $(OBJS)


fclean: clean
	rm -f $(NAME)


re: fclean all


.PHONY: all clean fclean re
